# Generated by Django 4.0.3 on 2024-03-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donation_updationdate_alter_donor_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='adminremark',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donationarea',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donationdate',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='idpic',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='volunteerremark',
        ),
    ]
