# Generated by Django 4.0.3 on 2024-04-06 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0004_remove_donation_adminremark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('userpic', models.FileField(null=True, upload_to='')),
                ('idpic', models.FileField(null=True, upload_to='')),
                ('aboutme', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('adminremark', models.CharField(max_length=300, null=True)),
                ('updateiondate', models.DateField(null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
