# Generated by Django 4.0.3 on 2024-04-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_ngo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='deliveryloc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='ngoname',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
