# Generated by Django 4.0.3 on 2024-04-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_donation_deliveryloc_donation_ngoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='ngo_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='val_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='valname',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
